# Generated by Django 5.0.6 on 2024-05-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uav',
            name='daily_price',
        ),
        migrations.RemoveField(
            model_name='uav',
            name='weekly_price',
        ),
    ]
