# Generated by Django 5.0.6 on 2024-05-20 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_uav_daily_price_remove_uav_weekly_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uav',
            name='name',
        ),
    ]
