# Generated by Django 5.0.6 on 2024-05-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_uav_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='image',
            field=models.ImageField(default='', upload_to='rentalProject/static'),
            preserve_default=False,
        ),
    ]
