# Generated by Django 5.0.6 on 2024-05-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_uav_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='image_path',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
