# Generated by Django 5.0.6 on 2024-05-21 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_uav_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uav',
            name='image_path',
        ),
    ]
